### ISSUE TITLE
Initializing State and Specifying types

### ISSUE THREAD

**Issue by cooperhailey** [frol/bos-component-ts-starter#3]
I'm looking for guidance on how to properly initialize a state and specify types within ts project.

**Comment by Jamal-invoker** [comment]
And I've encountered an issue when calling a function from common.tsx that imports entire functions  into generated components. 

```
export function someFunction() {
  return "someFunction output";
}

export function someFunction2() {
  return "someFunction outputssssss";
}
```

```
import { someFunction } from "@/includes/common";

interface Props {
  color?: "red" | "green";
}

export default function (props: Props) {
  if (!props.color) {
    return "No color is specified!";
  }

  return (
    <>
      <h2 style={{ color: props.color }}>Component color is {props.color}.</h2>
      <p> Let's see someFunction output: {someFunction()}</p>
    </>
  );
}

```


The generated component will be -

/*
License: MIT
Author: frol.near
Homepage: https://github.com/frol/bos-component-ts-starter#readme
*/
// With the setup in this repo (see package.json and build.js), you can import
// individual files from src/includes/ folder. They will be inlined here
// before publishing.
/* INCLUDE: "includes/common.jsx" */
function someFunction() {
  return "someFunction output";
}

export function someFunction2() {
  return "someFunction outputssssss";
}
/* END_INCLUDE: "includes/common.jsx" */





function MainComponent(props) {
  if (!props.color) {
    return "No color is specified!";
  }

  return (
    <>
      <h2 style={{ color: props.color }}>Component color is {props.color}.</h2>
      <p> Let's see someFunction output: {someFunction()}</p>
    </>
  );
}

return MainComponent(props, context);

**Comment by cooperhailey** [comment]
And I've encountered another issue imports unused functions from includes at build time.

when calling a function from common.tsx that imports other functions into generated components.

```

export function someFunction() {
  return "someFunction output";
}

export function someFunction2() {
  return "someFunction outputssssss";
}

```

```
import { someFunction } from "@/includes/common";

interface Props {
  color?: "red" | "green";
}

export default function (props: Props) {
  if (!props.color) {
    return "No color is specified!";
  }

  return (
    <>
      <h2 style={{ color: props.color }}>Component color is {props.color}.</h2>
      <p> Let's see someFunction output: {someFunction()}</p>
    </>
  );
}
```

The generated component will be -

```
/*
License: MIT
Author: frol.near
Homepage: https://github.com/frol/bos-component-ts-starter#readme
/
// With the setup in this repo (see package.json and build.js), you can import
// individual files from src/includes/ folder. They will be inlined here
// before publishing.
/ INCLUDE: "includes/common.jsx" */
function someFunction() {
return "someFunction output";
}

export function someFunction2() {
return "someFunction outputssssss";
}
/* END_INCLUDE: "includes/common.jsx" */

function MainComponent(props) {
if (!props.color) {
return "No color is specified!";
}

return (
<>
<h2 style={{ color: props.color }}>Component color is {props.color}.
Let's see someFunction output: {someFunction()}


</>
);
}
return MainComponent(props, context);
```

**Comment by frol** [comment]
> And I've encountered another issue imports unused functions from includes at build time.

Yes, dead code elimination is not implemented yet. I have extracted that in a separate issue #4.

**Comment by frol** [comment]
> I'm looking for guidance on how to properly initialize a state and specify types within ts project.

Can you be more specific?

**Comment by cooperhailey** [comment]
> Can you be more specific?

That is  typescript integration throwing the "Cannot find name 'State'" error when using State from State API.

**Comment by frol** [comment]
@cooperhailey provide a minimum reproducible example, with the actual outcome vs expectations

**Comment by cooperhailey** [comment]
> @cooperhailey provide a minimum reproducible example, with the actual outcome vs expectations

![image](https://github.com/frol/bos-component-ts-starter/assets/89442236/c481aea2-77b2-476b-a2eb-d036901dd354)


how we use [near-social-vm-types](https://www.npmjs.com/package/near-social-vm-types) in bos-component-ts-starter

**Comment by frol** [comment]
@cooperhailey Have you installed dependencies? (`npm install`)

Yet, I don't know how can we properly type `state` global variable based on the `State.init` method call. Raised the issue on https://github.com/shelegdmitriy/near-social-vm-types/issues/1. The hack is to make it `any` by adding the following line at the end of `global.d.ts`:

```ts
declare const state: any;
```

**Comment by frol** [comment]
@cooperhailey Consider using `useState` hook: https://github.com/NearSocial/VM/releases/tag/2.4.0

**Comment by yannvr** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
LPicker, @cartierhao, @jin10086, @yinguangyao, @zhiyuanFan, @mxn21, @redfast00, @clin003, @lwmukx1208, @michaelzhang1994, @xieyang94, @FannieHF, @jocongmin, @zw1122121, @scullabyte, @andyiac, @itchina110, @jack2020, @RobinChenJP, @TetragrammatonHermit

**Comment by zhiyuanFan** [comment]
您的来信已收到，我会尽快回复您，谢谢！

**Comment by jocongmin** [comment]
您的邮件我已收到，谢谢。

**Comment by denbite** [comment]
I've just opened PullRequest, which adds declarations for React-like functions (https://github.com/shelegdmitriy/near-social-vm-types/pull/3) to avoid using `State.init()`

**Comment by zhiyuanFan** [comment]
您的来信已收到，我会尽快回复您，谢谢！

**Comment by jocongmin** [comment]
您的邮件我已收到，谢谢。

**Comment by frol** [comment]
I think we can close this issue by saying that users should update their `near-social-vm-types` to 1.1.0+ (see package.json), and use `useState` instead of the legacy `State.init`
